# CodeRabbit Configuration for Happyland Gardens

# Language and framework awareness
language: typescript
frameworks:
  - nextjs
  - react
  - tailwindcss

# Review settings
reviews:
  # Request changes for critical issues
  request_changes_workflow: true

  # Auto-approve minor changes
  auto_approve:
    enabled: false

  # Review focus areas
  focus_areas:
    - security
    - performance
    - accessibility
    - best_practices
    - code_quality
    - testing

# What to review
review_settings:
  # File patterns to review
  include:
    - "**/*.ts"
    - "**/*.tsx"
    - "**/*.js"
    - "**/*.jsx"
    - "**/*.css"

  # File patterns to ignore
  exclude:
    - "node_modules/**"
    - ".next/**"
    - "out/**"
    - "build/**"
    - "dist/**"
    - "*.config.js"
    - "*.config.ts"
    - "package-lock.json"

  # Maximum files to review per PR
  max_files: 50

# Issue detection
checks:
  # Code quality
  code_quality:
    enabled: true
    severity: warning

  # Security vulnerabilities
  security:
    enabled: true
    severity: error

  # Performance issues
  performance:
    enabled: true
    severity: warning

  # Accessibility issues
  accessibility:
    enabled: true
    severity: warning

  # Best practices
  best_practices:
    enabled: true
    severity: info

  # Unused code
  unused_code:
    enabled: true
    severity: info

  # TypeScript specific
  typescript:
    strict_mode: true
    no_any: warning

  # React specific
  react:
    hooks_rules: error
    component_patterns: warning

# Custom rules for Happyland Gardens
custom_rules:
  - name: "No console.log in production"
    pattern: "console\\.log"
    severity: error
    message: "Remove console.log before merging to production"

  - name: "Use Next.js Image component"
    pattern: "<img"
    severity: warning
    message: "Use Next.js Image component for better performance"

  - name: "Prefer named exports"
    pattern: "export default"
    severity: info
    message: "Consider using named exports for better tree-shaking"

  - name: "Add alt text to images"
    pattern: "<Image[^>]+(?!alt=)"
    severity: error
    message: "All images must have alt text for accessibility"

# Comment settings
comments:
  # Comment on every file reviewed
  per_file: true

  # Summary comment on PR
  summary: true

  # Tone of comments
  tone: professional

  # Include code suggestions
  suggestions: true

  # Include fix examples
  fix_examples: true

# AI behavior
ai_settings:
  # How verbose should CodeRabbit be
  verbosity: moderate

  # Should CodeRabbit ask questions
  ask_questions: true

  # Should CodeRabbit provide context
  provide_context: true

  # Learning from previous reviews
  learn_from_feedback: true

# Integration settings
integrations:
  github:
    enabled: true
    auto_label: true
    labels:
      - "needs-review"
      - "coderabbit-reviewed"