# CodeRabbit Configuration for Happyland Gardens

# Language for review comments (human language, not programming)
language: en-US

reviews:
  profile: chill  # or 'assertive'
  request_changes_workflow: true

  # Path filters for what to review
  path_filters:
    - "**/*.ts"
    - "**/*.tsx"
    - "**/*.js"
    - "**/*.jsx"
    - "**/*.css"
    - "!node_modules/**"
    - "!.next/**"
    - "!out/**"
    - "!build/**"
    - "!dist/**"
    - "!*.config.js"
    - "!*.config.ts"
    - "!package-lock.json"

  # Custom path-specific instructions
  path_instructions:
    - path: "**/*.{ts,tsx}"
      instructions: |
        - Enforce TypeScript strict mode
        - Warn on usage of 'any' type
        - Check React hooks rules
        - Prefer named exports over default exports
        - Ensure proper type safety

    - path: "**/components/**/*.{ts,tsx}"
      instructions: |
        - Ensure Next.js Image component is used instead of <img>
        - Verify all images have alt text for accessibility
        - Flag console.log statements
        - Check for proper React component patterns
        - Ensure accessibility best practices (ARIA labels, semantic HTML)

    - path: "**/*.css"
      instructions: |
        - Ensure Tailwind utility classes are used correctly
        - Check for responsive design patterns
        - Verify color usage matches design system

  # Label configuration
  labeling_instructions:
    - label: "needs-review"
      instructions: "Apply to all PRs pending review"
    - label: "coderabbit-reviewed"
      instructions: "Apply after CodeRabbit completes review"

  auto_apply_labels: true

  # Enable various integrations
  tools:
    eslint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000

# GitHub integration
integrations:
  github:
    enabled: true
    auto_label: true
